apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - sh
            - /entrypoint.sh
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "nginx.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NGINX_DEBUG
              value: "{{ .Values.useDebugBinary }}"
        {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: {{ include "nginx.fullname" . }}
              mountPath: /etc/nginx/nginx.conf.tpl
              subPath: nginx.conf
            - name: {{ include "nginx.fullname" . }}
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
        {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- if .Values.dnsmasq.enabled }}
        - name: dnsmasq
          image: "janeczku/go-dnsmasq:release-1.0.5"
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
            - --hostsfile=/etc/hosts
            - --verbose
      {{- end }}
      volumes:
        - name: {{ include "nginx.fullname" . }}
          configMap:
            name: {{ include "nginx.fullname" . }}
            items:
              - key: nginx.conf
                path: nginx.conf
                mode: 292 # 0444
              - key: entrypoint.sh
                path: entrypoint.sh
                mode: 365 # 0555
    {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
